# Generated by Django 3.0.6 on 2020-05-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0002_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmart.Category'),
        ),
    ]
