# Generated by Django 3.0.6 on 2020-05-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0003_sub_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmart.Category')),
                ('sub_name', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmart.Sub_Category')),
            ],
        ),
    ]
