# Generated by Django 3.0.6 on 2020-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0004_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='add_product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add_product',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='add_product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
