# Generated by Django 3.0.6 on 2020-05-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0006_auto_20200507_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='sub_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
