# Generated by Django 3.0.6 on 2020-05-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0007_auto_20200511_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_product',
        ),
    ]
